### ISSUE TITLE
@cache_response doesn't seem to be working with DRF 2.4

### ISSUE THREAD

**Issue by ondrowan** [chibisov/drf-extensions#32]
I'm getting following exception while using DRF 2.4 and Django 1.7:

```
Traceback (most recent call last):
  File "/usr/lib/python3.3/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vagrant/.virtualenvs/project/lib/python3.3/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/home/vagrant/.virtualenvs/project/lib/python3.3/site-packages/django/core/handlers/base.py", line 210, in get_response
    response._closable_objects.append(request)
AttributeError: 'Response' object has no attribute '_closable_objects'
```

It works alright if I downgrade to DRF 2.3 or remove `@cache_response` from given view.
